[package]
name = "presenterm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
comrak = "0.18"
crossterm = { version = "0.27", features = ["serde"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
syntect = "5.1"
thiserror = "1"
viuer = "0.6"
