[package]
name = "presenterm"
authors = ["Matias Fontanini"]
description = "A terminal slideshow presentation tool"
repository = "https://github.com/mfontanini/presenterm"
license = "BSD-2-Clause"
version = "0.2.1"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive", "string"] }
comrak = { version = "0.19", default-features = false }
crossterm = { version = "0.27", features = ["serde"] }
hex = "0.4"
image = "0.24"
merge-struct = "0.1.0"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_with = "3.3"
syntect = "5.1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
unicode-width = "0.1"
viuer = "0.7.1"
colored = "2.0.4"

[dev-dependencies]
rstest = { version = "0.18", default-features = false }

[features]
default = []
sixel = ["viuer/sixel"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
